### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by ericsagnes** [styx-static/styx#1]
Post generation is quite slow essentially because `runCommand` is triggered multiple times per post.

One possibility would be to parse and convert all the posts for a directory in a single runCommand. It will make faster full builds, but maybe slower rebuilds (as single pages will not be cached in the nix-store and rebuild every time).

Another possibility would be to group the two `runCommand` for a post into a single one. That should slightly improve full build performance while keeping per page cache.

**Comment by ericsagnes** [comment]
> Another possibility would be to group the two runCommand for a post into a single one. That should slightly improve full build performance while keeping per page cache.

done in f2206d68dbdd9a878325aef592909a47a0492a5b.

**Comment by ericsagnes** [comment]
> One possibility would be to parse and convert all the posts for a directory in a single runCommand. It will make faster full builds, but maybe slower rebuilds (as single pages will not be cached in the nix-store and rebuild every time).

On small websites the number of pages is not so big so the generation time would not be _too_ long, so this will not make a big change.
On bigger websites, losing cache will quickly overcome any speed improvement per post parsing.

In short, this is not a good idea.

I let the issue open as there might be othe ways to improve the performance, but to be realistic, Styx killer feature will **never** be speed. (But thanks to Nix, Styx has one of the best caching system possible, and that somehow compensate its poor performance)

**Comment by danbst** [comment]
Why is runCommand slow? maybe it triggers nixpkgs evaluation every-time?

**Comment by ericsagnes** [comment]
At first, we were running 2 `runCommand` for parsing a post. Grouping that made things better, and actually adding commands in that `runCommand` is quite cheap. (there is an undocumented front matter parsing step in that `runCommand` that is almost transparent)

Styx is _relatively_ slow compared to other tools, and there is no way we can get on par with tools like Hugo on cold site generation. On warm generation, Nix cache really shines and the performance is not _that_ bad.

Other tools call directly libraries to parse markdown files, compared to that setting up an environment is quite costly, but again it is not that bad. And I think the flexibility of Styx brings a different value than generating a few more page per second. (For example, the github pages deploy worflow is utterly simple compared to [others](https://gohugo.io/tutorials/github-pages-blog/))

Anyway, this just got a first release so there is room for improvement :)

**Comment by ericsagnes** [comment]
Closed via d468905db90f5f69b5df8f2a3cf6c9ac4e91811a.
Turning `allowSubstitutes` to `false` made the performance to become very acceptable.
