### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#10]
As this is written in bash+nix, with no types, I guess a simple test suite is required to test
- package build
- all styx subcommands not to fail
- correct sample generation (links should always return OK 200)
- main site links should return OK 200

**Comment by ericsagnes** [comment]
I really would like to add a `checkPhase` to the derivation that did all that, but trying to run Styx in a nix-build environment doesn't work as it is trying to do a `nix-build` in a `nix-build`.

I guess I will have to make it a bash script until I find a way to run Styx in a nix-build.

**Comment by ericsagnes** [comment]
Still have rough edges, but done a first implementation in https://github.com/styx-static/styx/commit/ae23ef5f63e86865ebb06da85afabf53f9718771.
