### ISSUE TITLE
Github repo doesn't have link to main site

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#14]
There is a link from https://styx-static.github.io/styx-site/ to this repo, but I can't link-access https://styx-static.github.io/styx-site/documentation.html from github repo. 

I think the link should be either in project description or at start of README

**Comment by ericsagnes** [comment]
Thanks for noticing!

Closed via 1f259b7c49ff43b1e8a9131d87a5fc9f034b9360 and added link in project description.
