### ISSUE TITLE
styx serve broken

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#16]
I'm using master at 79bad12c942f6ea8ac2d42795e295f9c554c406f revision

```
$ styx serve
/nix/store/mpx5xbc90sm8rw0sklcplh7djdcrs987-nvhz5j7lgg8v4q8bqhv6nfisdd0sc87h-styx-0.3.0-dev/bin/styx: unknown option `serve'
```

**Comment by ericsagnes** [comment]
Sorry, there was a typo `styx.sh`.

Fixed in cd3c9d366245934edd043b70764b2db6a112195e.

Will add `serve` to the test suite too.
