### ISSUE TITLE
Styx feedback

### ISSUE THREAD

**Issue by zimbatm** [styx-static/styx#25]
Hi, thanks for writing Styx.

Feel free to close this issue as it's just a piece of feedback. Styx is a really cool idea and I think if you could align some of these expectations it would get better adoption.

As a user, when I ran the `styx new site ./some-dir` command I expected to get a folder with a top-level `default.nix` that would look like this:

```nix
{ pkgs ? import <nixpkgs> {} }: # potentially with a pinned nixpkgs or styx import
let
  inherit (pkgs.styx) mkStyx;
in
  mkStyx {
    name = "some-dir";

    src = ./pages;
    # all the config goes here

  }
```

And then I could run `nix-build` on it and get a generated website as an output derivation.

It's nice to have the styx cli for preview but the user should be able to build the website without.

That's it for now :)

**Comment by ericsagnes** [comment]
Thanks for the feedback!


> And then I could run nix-build on it and get a generated website as an output derivation.
> It's nice to have the styx cli for preview but the user should be able to build the website without.

Good idea, that is a nice feature to have. added in da27c7ded41ac220624120be6372f2519427d633.

---

Internally the cli call the [site builder](https://github.com/styx-static/styx/blob/master/src/nix/site-builder.nix), that contains just a `callPackage` call.

For example, the [debug](https://styx-static.github.io/styx-site/documentation/v0.6.0/index.html#_debugging) and the [deploy](https://styx-static.github.io/styx-site/documentation/v0.6.0/index.html#_nixops) section of the documentation show how to build a site directly from `nix-repl` and a NixOps deployement file without needing the cli.

With `nix-repl`:

```sh
$ nix-repl "<nixpkgs>"

nix-repl> showcase = callPackage (import "${styx-themes.showcase}/example/site.nix") {}

nix-repl> :b showcase.site
...
this derivation produced the following outputs:
  out -> /nix/store/ak6h49a9h7asysv91nf31nhd5h7fgzhi-styx-site
```

With NixOps:


```nix
{
  network.description = "Styx example";

  webserver = { config, pkgs, ... }: {
    deployment = {
      targetEnv = "virtualbox";
      virtualbox.memorySize = 1024;
      virtualbox.headless = true;
    };

    networking.firewall.allowedTCPPorts = [ 80 ];

    services.nginx = {
      enable = true;
      httpConfig = ''
        server {
          listen 80;
          location / {
            root ${(pkgs.callPackage ./site.nix {}).site};
          }
        }
      '';
    };
  };
}
```

**Comment by ericsagnes** [comment]
Closing in favor of #38
