### ISSUE TITLE
Interesting installation error case

### ISSUE THREAD

**Issue by lukego** [styx-static/styx#26]
I really like the brevity of this installation style:

```
nix-env -i $(nix-build http://...)
```

However there seems to be an interesting error case. If the `nix-build` fails for some reason, in the usual unix style of printing a message to stderr and exiting with non-zero status, then the shell will execute the expansion as:

```
nix-env -i
```

and this seems to cause `nix-env` to try to install every package in the whole of nixpkgs :).

I wonder if there is some simple way to avoid this particular error case?

**Comment by ericsagnes** [comment]
The best would be to ensure that the remote package builds fine by using some CI (travis can build nix expression quite well).

To avoid this problem, a solution would be to install from the derivation instead of the store product:

```
nix-env -i $(nix-instantiate http://...)
```

This moves the build step in the `nix-env` process, and throw an error if the package does not build:

```
nix-env -i $(nix-instantiate error.nix)                                                                                                                                                                                                
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
installing ‘styx-0.7.0-dev.drv’
these derivations will be built:
  /nix/store/j4vk8qsrjjsypv6158b2zwyczxa3dbkq-styx-0.7.0-dev.drv
  building path(s) ‘/nix/store/2h4l5aa4lbwsrx825vwh5bi81jml6mi6-styx-0.7.0-dev-lib’, ‘/nix/store/vs2w7ydavlpbyv2d0a01b6xjryfcdx0k-styx-0.7.0-dev’
  unpacking sources
  unpacking source archive /nix/store/hbg4h9mlfcc7k1ya373n6abnifxg6vqc-src
  source root is src
  patching sources
  configuring
  grep: Invalid range end
  no configure script, doing nothing
  building
  no Makefile, doing nothing
  installing
  builder for ‘/nix/store/j4vk8qsrjjsypv6158b2zwyczxa3dbkq-styx-0.7.0-dev.drv’ failed with exit code 1
  error: build of ‘/nix/store/j4vk8qsrjjsypv6158b2zwyczxa3dbkq-styx-0.7.0-dev.drv’ failed
  sh-4.4$ 
```

**Comment by lukego** [comment]
That does sound like a partial solution. I think the bad case still applies if `nix-instantiate` fails though e.g. due to a network problem on the download.

Here is one alternative that trades brevity for robustness:

```
nix-env -i $(nix-build http://... || echo --failed)
```

as in:

```
$ nix-env -i $(nix-instantiate http://localhost/ || echo --failed)
downloading ‘http://localhost/’... [0/0 KiB, 0.0 KiB/s]
error: unable to download ‘http://localhost/’: Couldn't connect to server (7)
error: unknown flag ‘--failed’
Try ‘nix-env --help’ for more information.
```

**Comment by ericsagnes** [comment]
> That does sound like a partial solution. I think the bad case still applies if nix-instantiate fails though e.g. due to a network problem on the download.

Good point. Maybe the best would be that `nix-env -i` do not try to install all the packages, as it is unlikely that this is what the user wants to do, and output an error message.

**Comment by ericsagnes** [comment]
Made an issue in the nix repository: https://github.com/NixOS/nix/issues/1334

**Comment by ericsagnes** [comment]
Closing in favor the aforementioned Nix issue.
