### ISSUE TITLE
styx doc: permission denied

### ISSUE THREAD

**Issue by plumps** [styx-static/styx#29]
> system: macOS Sierra
> nix: 1.11.9
> nixpkgs: master

Hi, 

I am on Nixpkgs (master) on macOS and executing `styx doc` after generating the example data, leads to

`/Users/plumps/.nix-profile/bin/styx: line 252: /nix/store/prr875wd0966mm220ykgsqh15ymqldil-styx-0.6.0/share/doc/styx/index.html: Permission denied`

**Comment by ericsagnes** [comment]
This might be due because`$BROWSER` is not defined.
Does running `BROWSER=open styx doc` changes anything?

**Comment by plumps** [comment]
Yeah, that ~~fixed~~ made it work.

**Comment by ericsagnes** [comment]
Great!
Closing via 6fb140d1ee5cd9c0799d762dd8905c5e398b571d that add an error message if `$BROWSER` is not set.
