### ISSUE TITLE
Make builds deterministict

### ISSUE THREAD

**Issue by zimbatm** [styx-static/styx#3]
Following https://github.com/NixOS/nixos-weekly/issues/23#issuecomment-251311406

Ideally the update would be derived from the file mtimes. If all the files haven't changed the update becomes a noop.

Ideally the file mtimes are somehow pinned to the git commit times. See https://github.com/rosylilly/git-set-mtime

**Comment by zimbatm** [comment]
nix resets all the file mtimes to 0 to avoid reproducibility issues so that might have to be done outside of the build, or by querying the .git/ DB. Like `git log -1 --pretty=format:%at`

**Comment by ericsagnes** [comment]
Implemented for the styx cli command in 00cb4e3112ff9442dee66b1a31425c402d83dad2.

Dealing with the Nix store will require a different way, but should be addressed when the wrapper function is introduced.

Closing for now, feel free to re-open if you consider the fix is incomplete.
