### ISSUE TITLE
`git push`  in gh-pages dir unsets the CNAME created by github and thus breaks the website

### ISSUE THREAD

**Issue by sjmackenzie** [styx-static/styx#30]
### steps to reproduce
* set the custom CNAME in the gh-pages settings page.
* run `styx deploy --gh-pages`
* run `git push origin gh-pages`

### expected behaviour
* the push doesn't have any conflicts
* the website doesn't break on the `domain.tld`

### actual behaviour 
* the push conflicts as github creates a file called `gh-pages/CNAME` in the root directory. Thus one has to `git push origin gh-pags -f` to force it.

### potential solution
* in the `conf.nix` file it might be possible to set an attribute called `cname = "domain.tld";`, this then writes a file called `gh-pages/CNAME` with the contents of "domain.tld" in it.

**Comment by ericsagnes** [comment]
`conf.nix` can be freely extended.

At the moment, there are a few way you can add custom files to the generated site:

- Adding it to a theme `files` directory, usually `themes.THEME.files`, all the files in this directory are copied verbatim to the generated site.
- Add a `postGen` attribute to `lib.mkSite`, eg:

```nix
  site = lib.mkSite {
    inherit files pageList;
    postGen = ''
      echo "domain.ltd" > $out/CNAME
    '';
  }
```

So it is totally possible for example to add a cname into `conf.nix`:

```
   CNAME = "domain.tld";
```

and to use it in `postGen` to generate `CNAME`:

```nix
  site = lib.mkSite {
    inherit files pageList;
    postGen = lib.optionalString (conf ? CNAME) ''echo "${conf.CNAME}" > $out/CNAME'';
  }
```

**Comment by 10long** [comment]
なるほどね〜
