### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by sjmackenzie** [styx-static/styx#43]
#41 was a show stopper for a long time, could we make a new release so we can point nixpkgs at latest working release?

**Comment by ericsagnes** [comment]
Done in https://github.com/styx-static/styx/commit/0f0a878156eac416620a177cc030fa9f2f69b1b8

**Comment by sjmackenzie** [comment]
thanks!

**Comment by sjmackenzie** [comment]
at what point does 0.7.2 show up here: https://github.com/styx-static/styx/releases ?
