### ISSUE TITLE
error: attribute 'lib' missing

### ISSUE THREAD

**Issue by Renha** [styx-static/styx#58]
I'm trying to follow https://styx-static.github.io/styx-site/documentation/ on previewing the hello world page. I fail. When using current unstable styx from nixpkgs, I get following error:

```
$ styx preview
error: attribute 'lib' missing, at /nix/store/...-styx-0.7.2/share/styx-src/derivation.nix:64:15
(use '--show-trace' to show detailed location information)
---
Error: Site could not been built, fix the errors and run the command again.
The '--show-trace' flag can be used to show debug information.
```

Ok, I thought, let's use the latest version of styx instead, but the error only became more early:
```
$ nix-shell -p $(nix-build https://github.com/styx-static/styx/archive/latest.tar.gz)
error: attribute 'lib' missing, at /nix/store/...-latest.tar.gz/derivation.nix:13:13
(use '--show-trace' to show detailed location information)
```

So the styx doesn't work completely.

**Comment by siraben** [comment]
Ah, this is due to https://github.com/NixOS/nixpkgs/issues/108938. I can push a fix soon.
