### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#6]
Documentation link broken in line "Then have a look to the --->documentation<--- to learn how to customize your site."

**Comment by danbst** [comment]
it refers to https://styx-static.github.io/documentation.html but should to https://styx-static.github.io/styx-site/documentation.html

**Comment by ericsagnes** [comment]
Thanks, fixed in https://github.com/styx-static/styx-site/commit/c783a3b5dfdd844a52545a467a73724f53c50f71
