### ISSUE TITLE
date: invalid date ‘@’

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#7]
I was following steps on top page:

```
[nix-shell:~/dev/styx]$ styx new myblog
date: invalid date ‘@’
```

**Comment by danbst** [comment]
guess, it is here

https://github.com/styx-static/styx/blob/master/src/styx.sh#L47

**Comment by danbst** [comment]
So, I've hotfixed that, and now I have this:

```
[nix-shell:~/dev/styx/styx/myblog]$ styx serve
error: getting attributes of path ‘/home/danbst/dev/styx/styx/myblog/pages/about.md’: No such file or directory
(use ‘--show-trace’ to show detailed location information)
```

**Comment by ericsagnes** [comment]
Thanks for reporting!

Closed via https://github.com/styx-static/styx/commit/a0263225bb97205e6e18159ed3bc53634e7deefb.
