### ISSUE TITLE
styx server should respect conf.nix parameter `siteUrl`

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#8]
styx server should respect conf.nix parameter `siteUrl`

this is IMO, because I'd like to test it on remote server, and now `styx serve` pins my site to 127.0.0.1

**Comment by ericsagnes** [comment]
There was a bad naming decision with `serve` as it was meant for preview and I didn't had in mind to serve directly a site with it.

So a few changes were introduced:
- New `Styx serve` flags:
  - `--server-host HOST` flag to set the hostname or ip the server will listen
  - `-site-url URL` to override `conf.siteUrl`
  - `--detach` to run the server in background
- `styx serve` honors `conf.siteUrl`
- A new `styx preview`, that is just an alias to `styx serve --site-url "http://HOST:PORT"`

But note that `styx serve` is mainly for testing purpose and a "real" web server should be preferred when possible.

Closed via https://github.com/styx-static/styx/commit/1d92e77328ad9a7ef1545f43c4c2572455c641d8
